import { WORLD_BOUNDARY } from '../world/world-collision';

export { WORLD_BOUNDARY };

export const MAX_WORLD_MEMBERS = 8;
export const MAX_AVATAR_BROADCASTS_PER_SECOND = 8;
export const AVATAR_MIN_BROADCAST_INTERVAL_MS = 1000 / MAX_AVATAR_BROADCASTS_PER_SECOND;
export const AVATAR_POSITION_DELTA_THRESHOLD = 0.08;
export const AVATAR_ROTATION_DELTA_DEGREES = 3;
export const AVATAR_ROTATION_DELTA_RADIANS = (AVATAR_ROTATION_DELTA_DEGREES * Math.PI) / 180;
export const AVATAR_KEEPALIVE_INTERVAL_MS = 2000;
export const AVATAR_PAYLOAD_TARGET_BYTES = 512;
export const MAX_REALTIME_EVENT_BYTES = 2048;
export const MAX_PRESENCE_ID_LENGTH = 128;
export const MIN_SEQUENCE = 1;
